# Site Build Settings
future: true

# jekyll-paginate configuration
paginate:            50

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "旅行熱炒店PODCAST X JEROME"
description:	       "探索冷門路線、人文史地與國際議題的PODCAST節目"
author:              "Jerome Yang"
thumbnail:           "https://imgur.com/UcBMib5.jpg"
website:             "https://ltsoj.com/"
email:               "travel.wok@ltsoj.com"

# Defaults
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "post"
  -
    scope:
      type: "episodes"
    values:
      layout: "episode"
  -
    scope:
      type: "guests"
    values:
      layout: "profile"
  -
    scope:
      type: "maps"
    values:
      layout: "map"

collections:
  episodes:
    output: true
    permalink: /podcast-:name
  pages:
    output: true
    permalink: /:name
  guests:
    output: true
    permalink: /guest/:name
  maps:
    output: true
    permalink: /map/:name
  extensions: {}
