# Site Build Settings
future: true

# jekyll-paginate configuration - disabled
# paginate:            50

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "旅行熱炒店：世界地理人文探索頻道"
description:	       "在旅行的路上，不斷挖掘那些人事物背後的故事！"
author:              "Jerome Yang"
thumbnail:           "https://i.imgur.com/BZpD6XW.jpg"
website:             "https://ltsoj.com/"
email:               "travel.wok@ltsoj.com"
author_title:        "旅行熱炒店主廚Jerome"

# Defaults
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "post"
  -
    scope:
      type: "episodes"
    values:
      layout: "episode"
  -
    scope:
      type: "guests"
    values:
      layout: "profile"
  -
    scope:
      type: "maps"
    values:
      layout: "map"

collections:
  episodes:
    output: true
    permalink: /podcast-:name
  pages:
    output: true
    permalink: /:name
  guests:
    output: true
    permalink: /guest/:name
  maps:
    output: true
    permalink: /map/:name
  extensions: {}
