# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

social:
- icon: 'fa-brands fa-facebook'
  link: 'https://www.facebook.com/travel.wok'
- icon: 'fa-brands fa-instagram'
  link: 'https://instagram.com/travel.wok'
- icon: 'fa-solid fa-envelope'
  link: 'mailto:travel.wok@ltsoj.com'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_date_prefix: 'Written on'

# Featured on homepage
features:
- title: 挑戰最高難度自助旅行：一個人的西非三國（貝南、多哥、迦納）
  excerpt: 西非可以說是全世界旅遊難度最高、也最少遊客踏足的地區；然而，這裡有著別的地方看不到的文化景觀、往昔非洲帝國的遺跡，以及見證奴隸貿易歷史的場景，再加上還未被觀光業污染的太嚴重，這使得西非具有一種讓人覺得「因為神秘、因此更應該前往」的獨特魅力。
  image: https://imgur.com/JoLD34z.jpg
  url: /west-africa
- title: 被打翻的族群調色盤：縱橫高加索三國（喬治亞、亞塞拜然、亞美尼亞）
  excerpt: 歐亞交界處、面積不大的一片山區裡，有著積累數千年的獨特文化，無數個互不相通的語言，又可以見到拜占庭、波斯、土耳其、蘇聯影響的痕跡，簡直就像個被打翻了的族群調色盤。這究竟是一個怎樣的地方？一起來看看我2019年5月的旅行見聞吧！
  image: assets/img/IMG_3379.JPG
  url: /caucasus
- title: 北非，其實沒那麼神秘：感恩節的摩洛哥之旅
  excerpt: 聽到北非，想到的不外乎是撒哈拉沙漠、阿拉伯語、遊牧民族等充滿神秘色彩的元素，而這種神秘感更讓人心生嚮往；不過就在我2018年11月親自前往摩洛哥之後，才發現原來這裡不但一點都不神秘，反而是個觀光化程度高到嚇人的國家⋯⋯
  image: https://lifetimesojournertravel.files.wordpress.com/2018/12/b9dc3-img_9435.jpg
  url: /morocco
- title: 從絲路到西伯利亞鐵路：穿越中亞北亞的42天大旅行
  excerpt: 2018年5到6月之間，利用換工作的空檔，我從烏茲別克出發，沿著絲路通過吉爾吉斯進入中國新疆，再由內蒙古進入西伯利亞，然後橫跨整個俄羅斯，旅程結束在芬蘭赫爾辛基。這趟翻過了帕米爾高原、造訪了貝加爾湖、搭乘了西伯利亞鐵路的42天大旅行，是我自主旅行迄今最勇敢的嘗試，也讓我看到短途旅遊中難以察覺的複雜地理現象⋯⋯
  image: https://lifetimesojournertravel.files.wordpress.com/2018/09/f5e1e-f6593152.jpg
  url: /grand-trip

# Showcase
showcase:
- popup2023
- xin2023